version: '3.8'
services:
  kibana:
    image: jamesgarside/kibana:7.9.3
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    deploy:
      placement:
        constraints:
          - "node.hostname==docker-1"
    networks:
      - elastic
    ports: 
      - "5601:5601"

networks:
  elastic:
    driver: overlay